import { CakeItem } from './types';

// Real high-quality images generated by the image tool
import heroLuxuryImg from './assets/images/hero_luxury_cake_1784502950164.jpg';
import weddingMinimalImg from './assets/images/wedding_minimal_cake_1784502965098.jpg';
import chocolateDripImg from './assets/images/chocolate_drip_cake_1784502978296.jpg';
import floralArtImg from './assets/images/floral_art_cake_1784502989963.jpg';

export const CAKE_GALLERY: CakeItem[] = [
  {
    id: 'wedding-1',
    name: 'The Gilded Rose Wedding Cake',
    description: 'An breathtaking, three-tiered masterpiece adorned with gold leaf detailing and delicate white sugar roses. A timeless centerpiece designed for luxurious celebrations.',
    category: 'wedding',
    image: heroLuxuryImg,
    priceEst: '$650+',
    flavors: ['Classic Vanilla Bean', 'Champagne & Raspberry', 'Salted Caramel Pecan'],
    servings: '75 - 100',
    features: ['24k Gold Leaf Accents', 'Handcrafted Sugar Flowers', 'Custom Tier Heights']
  },
  {
    id: 'minimal-1',
    name: 'Eucalyptus Minimalist Tier',
    description: 'Elegant, modern wedding cake featuring delicate textured rustic buttercream frosting, adorned with hand-selected sprigs of fresh green eucalyptus and micro-florals.',
    category: 'minimalist',
    image: weddingMinimalImg,
    priceEst: '$320+',
    flavors: ['Lemon Elderflower', 'Almond Amaretto', 'White Chocolate Matcha'],
    servings: '35 - 50',
    features: ['Textured Buttercream', 'Fresh Organic Botanical Accents', 'Contemporary Clean Design']
  },
  {
    id: 'chocolate-1',
    name: 'Decadent Ganache Drip Cake',
    description: 'Indulgent custom celebration cake smothered in glossy dark chocolate ganache, decorated with gold-painted chocolate macarons, fresh blackberries, and delicate dustings of edible gold.',
    category: 'chocolate',
    image: chocolateDripImg,
    priceEst: '$180+',
    flavors: ['Double Belgian Chocolate', 'Hazelnut Praline', 'Espresso Fudge'],
    servings: '15 - 25',
    features: ['Signature Drip Artistry', 'Artisanal Macaron Toppings', 'Gold Powder Dusting']
  },
  {
    id: 'botanical-1',
    name: 'Pressed Floral Watercolor Cake',
    description: 'A sophisticated art-focused creation iced in smooth cream-colored Swiss meringue buttercream, embellished with hand-painted watercolor florals and organic pressed petals.',
    category: 'botanical',
    image: floralArtImg,
    priceEst: '$220+',
    flavors: ['Earl Grey Lavender', 'Pistachio Rosewater', 'Red Velvet Berry'],
    servings: '20 - 30',
    features: ['Edible Painting Techniques', 'Real Pressed Organic Petals', 'Ultra-Smooth Swiss Meringue Buttercream']
  }
];

export const FLAVORS = [
  { id: 'chocolate', name: 'Double Belgian Chocolate', desc: 'Rich, moist chocolate cake with dark chocolate ganache filling' },
  { id: 'vanilla', name: 'Classic Madagascar Vanilla', desc: 'Fluffy sponge cake layered with pure vanilla bean buttercream' },
  { id: 'lemon', name: 'Lemon Elderflower', desc: 'Zesty lemon sponge infused with elderflower syrup and lemon curd' },
  { id: 'earlgrey', name: 'Earl Grey Lavender', desc: 'Sophisticated tea-infused sponge with organic lavender buttercream' },
  { id: 'pistachio', name: 'Pistachio Rosewater', desc: 'Grounded toasted pistachio sponge with subtle, sweet rosewater glaze' },
  { id: 'redvelvet', name: 'Red Velvet Berry', desc: 'Classic velvety crumb paired with a light, tangy raspberry cream cheese' }
];

export const FILLINGS = [
  { id: 'swiss-buttercream', name: 'Vanilla Swiss Meringue Buttercream' },
  { id: 'chocolate-ganache', name: 'Glossy Dark Belgian Ganache' },
  { id: 'raspberry-compote', name: 'House-made Raspberry & Champagne Compote' },
  { id: 'salted-caramel', name: 'Artisanal Salted Caramel' },
  { id: 'pistachio-cream', name: 'Creamy Toasted Pistachio Paste' },
  { id: 'lemon-curd', name: 'Bright and Tangy Organic Lemon Curd' }
];

export const SIZES = [
  { id: 'tier-1-sm', name: '1-Tier Small (6")', servings: '8-12', basePrice: 95 },
  { id: 'tier-1-lg', name: '1-Tier Large (8")', servings: '15-20', basePrice: 145 },
  { id: 'tier-2-std', name: '2-Tiers Standard (6" + 8")', servings: '25-35', basePrice: 280 },
  { id: 'tier-3-std', name: '3-Tiers Luxe (6" + 8" + 10")', servings: '60-80', basePrice: 520 },
  { id: 'tier-3-grand', name: '3-Tiers Grand (8" + 10" + 12")', servings: '85-110', basePrice: 720 }
];

export const CONTACT_INFO = {
  phone: '+1 (555) 782-9922', // Prefilled contact
  whatsapp: '15557829922', // Clean number for link
  email: 'patisserie@etoilecakes.com',
  address: '142 Golden Leaf Boulevard, Atelier District',
  hours: 'Tue - Sat: 10:00 AM - 6:00 PM | Sun: By Consultation Only'
};
